# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "@kwsites/file-exists-1.1.1" = {
      name = "_at_kwsites_slash_file-exists";
      packageName = "@kwsites/file-exists";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@kwsites/file-exists/-/file-exists-1.1.1.tgz";
        sha512 = "m9/5YGR18lIwxSFDwfE3oA7bWuq9kdau6ugN4H2rJeyhFQZcG9AgSHkQtSD15a8WvTgfz9aikZMrKPHvbpqFiw==";
      };
    };
    "@kwsites/promise-deferred-1.1.1" = {
      name = "_at_kwsites_slash_promise-deferred";
      packageName = "@kwsites/promise-deferred";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@kwsites/promise-deferred/-/promise-deferred-1.1.1.tgz";
        sha512 = "GaHYm+c0O9MjZRu0ongGBRbinu8gVAMd2UZjji6jVmqKtZluZnptXGWhz1E8j8D2HJ3f/yMxKAUC0b+57wncIw==";
      };
    };
    "@octokit/app-14.0.2" = {
      name = "_at_octokit_slash_app";
      packageName = "@octokit/app";
      version = "14.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/app/-/app-14.0.2.tgz";
        sha512 = "NCSCktSx+XmjuSUVn2dLfqQ9WIYePGP95SDJs4I9cn/0ZkeXcPkaoCLl64Us3dRKL2ozC7hArwze5Eu+/qt1tg==";
      };
    };
    "@octokit/auth-app-6.0.4" = {
      name = "_at_octokit_slash_auth-app";
      packageName = "@octokit/auth-app";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-app/-/auth-app-6.0.4.tgz";
        sha512 = "TPmJYgd05ok3nzHj7Y6we/V7Ez1wU3ztLFW3zo/afgYFtqYZg0W7zb6Kp5ag6E85r8nCE1JfS6YZoZusa14o9g==";
      };
    };
    "@octokit/auth-oauth-app-7.0.1" = {
      name = "_at_octokit_slash_auth-oauth-app";
      packageName = "@octokit/auth-oauth-app";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-oauth-app/-/auth-oauth-app-7.0.1.tgz";
        sha512 = "RE0KK0DCjCHXHlQBoubwlLijXEKfhMhKm9gO56xYvFmP1QTMb+vvwRPmQLLx0V+5AvV9N9I3lr1WyTzwL3rMDg==";
      };
    };
    "@octokit/auth-oauth-device-6.0.1" = {
      name = "_at_octokit_slash_auth-oauth-device";
      packageName = "@octokit/auth-oauth-device";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-oauth-device/-/auth-oauth-device-6.0.1.tgz";
        sha512 = "yxU0rkL65QkjbqQedgVx3gmW7YM5fF+r5uaSj9tM/cQGVqloXcqP2xK90eTyYvl29arFVCW8Vz4H/t47mL0ELw==";
      };
    };
    "@octokit/auth-oauth-user-4.0.1" = {
      name = "_at_octokit_slash_auth-oauth-user";
      packageName = "@octokit/auth-oauth-user";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-oauth-user/-/auth-oauth-user-4.0.1.tgz";
        sha512 = "N94wWW09d0hleCnrO5wt5MxekatqEJ4zf+1vSe8MKMrhZ7gAXKFOKrDEZW2INltvBWJCyDUELgGRv8gfErH1Iw==";
      };
    };
    "@octokit/auth-token-4.0.0" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-4.0.0.tgz";
        sha512 = "tY/msAuJo6ARbK6SPIxZrPBms3xPbfwBrulZe0Wtr/DIY9lje2HeV1uoebShn6mx7SjCHif6EjMvoREj+gZ+SA==";
      };
    };
    "@octokit/auth-unauthenticated-5.0.1" = {
      name = "_at_octokit_slash_auth-unauthenticated";
      packageName = "@octokit/auth-unauthenticated";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-unauthenticated/-/auth-unauthenticated-5.0.1.tgz";
        sha512 = "oxeWzmBFxWd+XolxKTc4zr+h3mt+yofn4r7OfoIkR/Cj/o70eEGmPsFbueyJE2iBAGpjgTnEOKM3pnuEGVmiqg==";
      };
    };
    "@octokit/core-5.1.0" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-5.1.0.tgz";
        sha512 = "BDa2VAMLSh3otEiaMJ/3Y36GU4qf6GI+VivQ/P41NC6GHcdxpKlqV0ikSZ5gdQsmS3ojXeRx5vasgNTinF0Q4g==";
      };
    };
    "@octokit/endpoint-9.0.4" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "9.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-9.0.4.tgz";
        sha512 = "DWPLtr1Kz3tv8L0UvXTDP1fNwM0S+z6EJpRcvH66orY6Eld4XBMCSYsaWp4xIm61jTWxK68BrR7ibO+vSDnZqw==";
      };
    };
    "@octokit/graphql-7.0.2" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-7.0.2.tgz";
        sha512 = "OJ2iGMtj5Tg3s6RaXH22cJcxXRi7Y3EBqbHTBRq+PQAqfaS8f/236fUrWhfSn8P4jovyzqucxme7/vWSSZBX2Q==";
      };
    };
    "@octokit/oauth-app-6.1.0" = {
      name = "_at_octokit_slash_oauth-app";
      packageName = "@octokit/oauth-app";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/oauth-app/-/oauth-app-6.1.0.tgz";
        sha512 = "nIn/8eUJ/BKUVzxUXd5vpzl1rwaVxMyYbQkNZjHrF7Vk/yu98/YDF/N2KeWO7uZ0g3b5EyiFXFkZI8rJ+DH1/g==";
      };
    };
    "@octokit/oauth-authorization-url-6.0.2" = {
      name = "_at_octokit_slash_oauth-authorization-url";
      packageName = "@octokit/oauth-authorization-url";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/oauth-authorization-url/-/oauth-authorization-url-6.0.2.tgz";
        sha512 = "CdoJukjXXxqLNK4y/VOiVzQVjibqoj/xHgInekviUJV73y/BSIcwvJ/4aNHPBPKcPWFnd4/lO9uqRV65jXhcLA==";
      };
    };
    "@octokit/oauth-methods-4.0.1" = {
      name = "_at_octokit_slash_oauth-methods";
      packageName = "@octokit/oauth-methods";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/oauth-methods/-/oauth-methods-4.0.1.tgz";
        sha512 = "1NdTGCoBHyD6J0n2WGXg9+yDLZrRNZ0moTEex/LSPr49m530WNKcCfXDghofYptr3st3eTii+EHoG5k/o+vbtw==";
      };
    };
    "@octokit/openapi-types-20.0.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "20.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-20.0.0.tgz";
        sha512 = "EtqRBEjp1dL/15V7WiX5LJMIxxkdiGJnabzYx5Apx4FkQIFgAfKumXeYAqqJCj1s+BMX4cPFIFC4OLCR6stlnA==";
      };
    };
    "@octokit/plugin-paginate-graphql-4.0.1" = {
      name = "_at_octokit_slash_plugin-paginate-graphql";
      packageName = "@octokit/plugin-paginate-graphql";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-graphql/-/plugin-paginate-graphql-4.0.1.tgz";
        sha512 = "R8ZQNmrIKKpHWC6V2gum4x9LG2qF1RxRjo27gjQcG3j+vf2tLsEfE7I/wRWEPzYMaenr1M+qDAtNcwZve1ce1A==";
      };
    };
    "@octokit/plugin-paginate-rest-9.2.1" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "9.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-9.2.1.tgz";
        sha512 = "wfGhE/TAkXZRLjksFXuDZdmGnJQHvtU/joFQdweXUgzo1XwvBCD4o4+75NtFfjfLK5IwLf9vHTfSiU3sLRYpRw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-10.4.1" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "10.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-10.4.1.tgz";
        sha512 = "xV1b+ceKV9KytQe3zCVqjg+8GTGfDYwaT1ATU5isiUyVtlVAO3HNdzpS4sr4GBx4hxQ46s7ITtZrAsxG22+rVg==";
      };
    };
    "@octokit/plugin-retry-6.0.1" = {
      name = "_at_octokit_slash_plugin-retry";
      packageName = "@octokit/plugin-retry";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-retry/-/plugin-retry-6.0.1.tgz";
        sha512 = "SKs+Tz9oj0g4p28qkZwl/topGcb0k0qPNX/i7vBKmDsjoeqnVfFUquqrE/O9oJY7+oLzdCtkiWSXLpLjvl6uog==";
      };
    };
    "@octokit/plugin-throttling-8.2.0" = {
      name = "_at_octokit_slash_plugin-throttling";
      packageName = "@octokit/plugin-throttling";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-throttling/-/plugin-throttling-8.2.0.tgz";
        sha512 = "nOpWtLayKFpgqmgD0y3GqXafMFuKcA4tRPZIfu7BArd2lEZeb1988nhWhwx4aZWmjDmUfdgVf7W+Tt4AmvRmMQ==";
      };
    };
    "@octokit/request-8.2.0" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-8.2.0.tgz";
        sha512 = "exPif6x5uwLqv1N1irkLG1zZNJkOtj8bZxuVHd71U5Ftuxf2wGNvAJyNBcPbPC+EBzwYEbBDdSFb8EPcjpYxPQ==";
      };
    };
    "@octokit/request-error-5.0.1" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-5.0.1.tgz";
        sha512 = "X7pnyTMV7MgtGmiXBwmO6M5kIPrntOXdyKZLigNfQWSEQzVxR4a4vo49vJjTWX70mPndj8KhfT4Dx+2Ng3vnBQ==";
      };
    };
    "@octokit/types-12.6.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "12.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-12.6.0.tgz";
        sha512 = "1rhSOfRa6H9w4YwK0yrf5faDaDTb+yLyBUKOCV4xtCDB5VmIPqd/v9yr9o6SAzOAlRxMiRiCic6JVM1/kunVkw==";
      };
    };
    "@octokit/webhooks-12.1.2" = {
      name = "_at_octokit_slash_webhooks";
      packageName = "@octokit/webhooks";
      version = "12.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/webhooks/-/webhooks-12.1.2.tgz";
        sha512 = "+nGS3ReCByF6m+nbNB59x7Aa3CNjCCGuBLFzfkiJP1O3uVKKuJbkP4uO4t46YqH26nlugmOhqjT7nx5D0VPtdA==";
      };
    };
    "@octokit/webhooks-methods-4.1.0" = {
      name = "_at_octokit_slash_webhooks-methods";
      packageName = "@octokit/webhooks-methods";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/webhooks-methods/-/webhooks-methods-4.1.0.tgz";
        sha512 = "zoQyKw8h9STNPqtm28UGOYFE7O6D4Il8VJwhAtMHFt2C4L0VQT1qGKLeefUOqHNs1mNRYSadVv7x0z8U2yyeWQ==";
      };
    };
    "@octokit/webhooks-types-7.3.2" = {
      name = "_at_octokit_slash_webhooks-types";
      packageName = "@octokit/webhooks-types";
      version = "7.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/webhooks-types/-/webhooks-types-7.3.2.tgz";
        sha512 = "JWOoOgtWTFnTSAamPXXyjTY5/apttvNxF+vPBnwdSu5cj5snrd7FO0fyw4+wTXy8fHduq626JjhO+TwCyyA6vA==";
      };
    };
    "@types/aws-lambda-8.10.136" = {
      name = "_at_types_slash_aws-lambda";
      packageName = "@types/aws-lambda";
      version = "8.10.136";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/aws-lambda/-/aws-lambda-8.10.136.tgz";
        sha512 = "cmmgqxdVGhxYK9lZMYYXYRJk6twBo53ivtXjIUEFZxfxe4TkZTZBK3RRWrY2HjJcUIix0mdifn15yjOAat5lTA==";
      };
    };
    "@types/btoa-lite-1.0.2" = {
      name = "_at_types_slash_btoa-lite";
      packageName = "@types/btoa-lite";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/btoa-lite/-/btoa-lite-1.0.2.tgz";
        sha512 = "ZYbcE2x7yrvNFJiU7xJGrpF/ihpkM7zKgw8bha3LNJSesvTtUNxbpzaT7WXBIryf6jovisrxTBvymxMeLLj1Mg==";
      };
    };
    "@types/jsonwebtoken-9.0.6" = {
      name = "_at_types_slash_jsonwebtoken";
      packageName = "@types/jsonwebtoken";
      version = "9.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-9.0.6.tgz";
        sha512 = "/5hndP5dCjloafCXns6SZyESp3Ldq7YjH3zwzwczYnjxIT0Fqzk5ROSYVGfFyczIue7IUEj8hkvLbPoLQ18vQw==";
      };
    };
    "@types/node-20.11.25" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "20.11.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-20.11.25.tgz";
        sha512 = "TBHyJxk2b7HceLVGFcpAUjsa5zIdsPWlR6XHfyGzd0SFu+/NFgQgMAl96MSDZgQDvJAvV6BKsFOrt6zIL09JDw==";
      };
    };
    "aggregate-error-3.1.0" = {
      name = "aggregate-error";
      packageName = "aggregate-error";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aggregate-error/-/aggregate-error-3.1.0.tgz";
        sha512 = "4I7Td01quW/RpocfNayFdFVk1qSuoh0E7JrbRJ16nH01HhKFQ88INq9Sd+nd72zqRySlr9BmDA8xlEJ6vJMrYA==";
      };
    };
    "before-after-hook-2.2.3" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.3.tgz";
        sha512 = "NzUnlZexiaH/46WDhANlyR2bXRopNg4F/zuSA3OpZnllCUgRaOF2znDioDWrmbNVsuZk6l9pMquQB38cfBZwkQ==";
      };
    };
    "bottleneck-2.19.5" = {
      name = "bottleneck";
      packageName = "bottleneck";
      version = "2.19.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bottleneck/-/bottleneck-2.19.5.tgz";
        sha512 = "VHiNCbI1lKdl44tGrhNfU3lup0Tj/ZBMJB5/2ZbNXRCPuRCO7ed2mgcK4r17y+KB2EfuYuRaVlwNbAeaWGSpbw==";
      };
    };
    "btoa-lite-1.0.0" = {
      name = "btoa-lite";
      packageName = "btoa-lite";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/btoa-lite/-/btoa-lite-1.0.0.tgz";
        sha512 = "gvW7InbIyF8AicrqWoptdW08pUxuhq8BEgowNajy9RhiE86fmGAGl+bLKo6oB8QP0CkqHLowfN0oJdKC/J6LbA==";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha512 = "zRpUiDwd/xk6ADqPMATG8vc9VPrkck7T07OIx0gnjmJAnHnTVXNQG3vfvWNuiZIkwu9KrKdA1iJKfsfTVxE6NA==";
      };
    };
    "clean-stack-2.2.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
        sha512 = "4diC9HaTE+KRAMWhDhrGOECgWZxoevMc5TlkObMqNSsVU62PYzXZ/SMTjzyGAFF1YusgxGcSWTEXBhp0CPwQ1A==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "deprecation-2.3.1" = {
      name = "deprecation";
      packageName = "deprecation";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz";
        sha512 = "xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==";
      };
    };
    "ecdsa-sig-formatter-1.0.11" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
        sha512 = "nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      };
    };
    "indent-string-4.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
        sha512 = "EdDDZu4A2OyIK7Lr/2zG+w5jmbuk1DVBnEwREQvBzspBJkCEbRa8GxU1lghYcaGJCnRWibjDXlq779X1/y5xwg==";
      };
    };
    "jsonwebtoken-9.0.2" = {
      name = "jsonwebtoken";
      packageName = "jsonwebtoken";
      version = "9.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-9.0.2.tgz";
        sha512 = "PRp66vJ865SSqOlgqS8hujT5U4AOgMfhrwYIuIhfKaoSCZcirrmASQr8CX7cUg+RMih+hgznrjp99o+W4pJLHQ==";
      };
    };
    "jwa-1.4.1" = {
      name = "jwa";
      packageName = "jwa";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-1.4.1.tgz";
        sha512 = "qiLX/xhEEFKUAJ6FiBMbes3w9ATzyk5W7Hvzpa/SLYdxNtng+gcurvrI7TbACjIXlsJyr05/S1oUhZrc63evQA==";
      };
    };
    "jws-3.2.2" = {
      name = "jws";
      packageName = "jws";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-3.2.2.tgz";
        sha512 = "YHlZCB6lMTllWDtSPHz/ZXTsi8S00usEV6v1tjq8tOUZzw7DpSDWVXjXDre6ed1w/pd495ODpHZYSdkRTsa0HA==";
      };
    };
    "lodash.includes-4.3.0" = {
      name = "lodash.includes";
      packageName = "lodash.includes";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
        sha512 = "W3Bx6mdkRTGtlJISOvVD/lbqjTlPPUDTMnlXZFnVwi9NKJ6tiAk6LVdlhZMm17VZisqhKcgzpO5Wz91PCt5b0w==";
      };
    };
    "lodash.isboolean-3.0.3" = {
      name = "lodash.isboolean";
      packageName = "lodash.isboolean";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isboolean/-/lodash.isboolean-3.0.3.tgz";
        sha512 = "Bz5mupy2SVbPHURB98VAcw+aHh4vRV5IPNhILUCsOzRmsTmSQ17jIuqopAentWoehktxGd9e/hbIXq980/1QJg==";
      };
    };
    "lodash.isinteger-4.0.4" = {
      name = "lodash.isinteger";
      packageName = "lodash.isinteger";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isinteger/-/lodash.isinteger-4.0.4.tgz";
        sha512 = "DBwtEWN2caHQ9/imiNeEA5ys1JoRtRfY3d7V9wkqtbycnAmTvRRmbHKDV4a0EYc678/dia0jrte4tjYwVBaZUA==";
      };
    };
    "lodash.isnumber-3.0.3" = {
      name = "lodash.isnumber";
      packageName = "lodash.isnumber";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isnumber/-/lodash.isnumber-3.0.3.tgz";
        sha512 = "QYqzpfwO3/CWf3XP+Z+tkQsfaLL/EnUlXWVkIk5FUPc4sBdTehEqZONuyRt2P67PXAk+NXmTBcc97zw9t1FQrw==";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha512 = "oSXzaWypCMHkPC3NvBEaPHf0KsA5mvPrOPgQWDsbg8n7orZ290M0BmC/jgRZ4vcJ6DTAhjrsSYgdsW/F+MFOBA==";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha512 = "0wJxfxH1wgO3GrbuP+dTTk7op+6L41QCXbGINEmD+ny/G/eCqGzxyCsh7159S+mgDDcoarnBw6PC1PS5+wUGgw==";
      };
    };
    "lodash.once-4.1.1" = {
      name = "lodash.once";
      packageName = "lodash.once";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
        sha512 = "Sb487aTOCr9drQVL8pIxOzVhafOjZN9UU54hiN8PU3uAiSV7lx1yYNpbNmex2PK6dSJoNTSJUUswT651yww3Mg==";
      };
    };
    "lru-cache-10.2.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.2.0.tgz";
        sha512 = "2bIM8x+VAf6JT4bKAljS1qUWgMsqZRPGJS6FSahIMPVvctcNhyVp7AJu7quxOW9jwkryBReKZY5tY5JYv2n/7Q==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "octokit-3.1.2" = {
      name = "octokit";
      packageName = "octokit";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/octokit/-/octokit-3.1.2.tgz";
        sha512 = "MG5qmrTL5y8KYwFgE1A4JWmgfQBaIETE/lOlfwNYx1QOtCQHGVxkRJmdUJltFc1HVn73d61TlMhMyNTOtMl+ng==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "semver-7.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.0.tgz";
        sha512 = "EnwXhrlwXMk9gKu5/flx5sv/an57AkRplG3hTK68W7FRDN+k+OWBj65M7719OkA82XLBxrcX0KSHj+X5COhOVg==";
      };
    };
    "simple-git-3.22.0" = {
      name = "simple-git";
      packageName = "simple-git";
      version = "3.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-git/-/simple-git-3.22.0.tgz";
        sha512 = "6JujwSs0ac82jkGjMHiCnTifvf1crOiY/+tfs/Pqih6iow7VrpNKRRNdWm6RtaXpvvv/JGNYhlUtLhGFqHF+Yw==";
      };
    };
    "undici-types-5.26.5" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "5.26.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-5.26.5.tgz";
        sha512 = "JlCMO+ehdEIKqlFxk6IfVoAUVmgz7cU7zD/h9XZ0qzeosSHmUJVOzSQvvYSYWXkFXC+IfLKSIffhv0sVZup6pA==";
      };
    };
    "universal-github-app-jwt-1.1.2" = {
      name = "universal-github-app-jwt";
      packageName = "universal-github-app-jwt";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-github-app-jwt/-/universal-github-app-jwt-1.1.2.tgz";
        sha512 = "t1iB2FmLFE+yyJY9+3wMx0ejB+MQpEVkH0gQv7dR6FZyltyq+ZZO0uDpbopxhrZ3SLEO4dCEkIujOMldEQ2iOA==";
      };
    };
    "universal-user-agent-6.0.1" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.1.tgz";
        sha512 = "yCzhz6FN2wU1NiiQRogkTQszlQSlpWaw8SvVegAc+bDxbzHgh1vX8uIe8OYyMH6DwH+sdTJsgMl36+mSMdRJIQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "_at_mattpolzin_slash_harmony";
    packageName = "@mattpolzin/harmony";
    version = "4.0.2";
    src = ./.;
    dependencies = [
      sources."@kwsites/file-exists-1.1.1"
      sources."@kwsites/promise-deferred-1.1.1"
      sources."@octokit/app-14.0.2"
      sources."@octokit/auth-app-6.0.4"
      sources."@octokit/auth-oauth-app-7.0.1"
      sources."@octokit/auth-oauth-device-6.0.1"
      sources."@octokit/auth-oauth-user-4.0.1"
      sources."@octokit/auth-token-4.0.0"
      sources."@octokit/auth-unauthenticated-5.0.1"
      sources."@octokit/core-5.1.0"
      sources."@octokit/endpoint-9.0.4"
      sources."@octokit/graphql-7.0.2"
      sources."@octokit/oauth-app-6.1.0"
      sources."@octokit/oauth-authorization-url-6.0.2"
      sources."@octokit/oauth-methods-4.0.1"
      sources."@octokit/openapi-types-20.0.0"
      sources."@octokit/plugin-paginate-graphql-4.0.1"
      sources."@octokit/plugin-paginate-rest-9.2.1"
      sources."@octokit/plugin-rest-endpoint-methods-10.4.1"
      sources."@octokit/plugin-retry-6.0.1"
      sources."@octokit/plugin-throttling-8.2.0"
      sources."@octokit/request-8.2.0"
      sources."@octokit/request-error-5.0.1"
      sources."@octokit/types-12.6.0"
      sources."@octokit/webhooks-12.1.2"
      sources."@octokit/webhooks-methods-4.1.0"
      sources."@octokit/webhooks-types-7.3.2"
      sources."@types/aws-lambda-8.10.136"
      sources."@types/btoa-lite-1.0.2"
      sources."@types/jsonwebtoken-9.0.6"
      sources."@types/node-20.11.25"
      sources."aggregate-error-3.1.0"
      sources."before-after-hook-2.2.3"
      sources."bottleneck-2.19.5"
      sources."btoa-lite-1.0.0"
      sources."buffer-equal-constant-time-1.0.1"
      sources."clean-stack-2.2.0"
      (sources."debug-4.3.4"
        // {
          dependencies = [
            sources."ms-2.1.2"
          ];
        })
      sources."deprecation-2.3.1"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."indent-string-4.0.0"
      sources."jsonwebtoken-9.0.2"
      sources."jwa-1.4.1"
      sources."jws-3.2.2"
      sources."lodash.includes-4.3.0"
      sources."lodash.isboolean-3.0.3"
      sources."lodash.isinteger-4.0.4"
      sources."lodash.isnumber-3.0.3"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.once-4.1.1"
      sources."lru-cache-10.2.0"
      sources."ms-2.1.3"
      sources."octokit-3.1.2"
      sources."once-1.4.0"
      sources."safe-buffer-5.2.1"
      (sources."semver-7.6.0"
        // {
          dependencies = [
            sources."lru-cache-6.0.0"
          ];
        })
      sources."simple-git-3.22.0"
      sources."undici-types-5.26.5"
      sources."universal-github-app-jwt-1.1.2"
      sources."universal-user-agent-6.0.1"
      sources."wrappy-1.0.2"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Instill harmony between GitHub collaborators.";
      homepage = "https://github.com/mattpolzin/harmony#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src =
        nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
